# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-16 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imgApartMent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default=1, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='imgDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('idate', models.CharField(max_length=64)),
                ('folder', models.CharField(default='', max_length=128)),
                ('author', models.CharField(default='', max_length=32)),
                ('keyword', models.CharField(default='', max_length=128)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jojogallery.imgApartMent')),
            ],
        ),
        migrations.CreateModel(
            name='imgUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iurl', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/')),
                ('idate', models.CharField(max_length=64)),
                ('iname', models.CharField(max_length=64)),
                ('iChecked', models.BooleanField(default=False)),
                ('iDevice', models.CharField(default='avatar', max_length=64)),
                ('iCaption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jojogallery.imgDetail')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('permission', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
